spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dabook
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 560514553681-ss3r60q99cig6he9omnc7q1i1r5reg6i.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
#            redirect-uri: http://localhost:8080/dabook
#            redirect-uri: http://localhost:8080/dabook/main/login/oauth2/code/google

          naver:
            client-id: BdkgYlkWg4sx2t9svt0s
            client-secret: 3teflWFjMW
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


server:
  servlet:
    encoding:
      force: true

    jsp:
      init-parameters:
        development: true

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace
    

